apiVersion: v1
kind: Pod
metadata:
  name: is-attack
  labels:
    app: ubuntu
spec:
  containers:
  - image: jcarabantes/intense-security-audit-utils:1.0.0
    command:
      - "sleep"
      - "360000" 
    imagePullPolicy: IfNotPresent
    name: is-attack
  restartPolicy: Never
